DROP TABLE IF EXISTS users;

CREATE TABLE USERS (
id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(20) NOT NULL,
address_line VARCHAR(250) NOT NULL,
city VARCHAR(50) NOT NULL,
county VARCHAR(50) NOT NULL,
postcode VARCHAR(10) NOT NULL
);
